package org.bukkit.entity;

import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.util.Vector;
import java.util.UUID;

public interface Entity {
    UUID getUniqueId();
    String getName();
    Location getLocation();
    World getWorld();
    double getX();
    double getY();
    double getZ();
    boolean teleport(Location location);
    boolean teleport(Entity destination);
    Vector getVelocity();
    void setVelocity(Vector velocity);
    boolean isOnGround();
    boolean isDead();
    boolean isValid();
    void remove();
    int getEntityId();
    int getFireTicks();
    void setFireTicks(int ticks);
    int getMaxFireTicks();
    float getFallDistance();
    void setFallDistance(float distance);
    boolean isInsideVehicle();
    boolean leaveVehicle();
    boolean eject();
    Entity getVehicle();
    void setCustomName(String name);
    String getCustomName();
    void setCustomNameVisible(boolean flag);
    boolean isCustomNameVisible();
    void setGlowing(boolean flag);
    boolean isGlowing();
    void setInvulnerable(boolean flag);
    boolean isInvulnerable();
    void setSilent(boolean flag);
    boolean isSilent();
    boolean hasGravity();
    void setGravity(boolean gravity);
    int getPortalCooldown();
    void setPortalCooldown(int cooldown);
    int getTicksLived();
    void setTicksLived(int value);
    void sendMessage(String message);
    void sendMessage(String[] messages);
    boolean isOp();
    void setOp(boolean value);
    void setMetadata(String metadataKey, org.bukkit.metadata.MetadataValue metadataValue);
    java.util.List<org.bukkit.metadata.MetadataValue> getMetadata(String metadataKey);
    boolean hasMetadata(String metadataKey);
    void removeMetadata(String metadataKey, org.bukkit.plugin.Plugin plugin);
    org.bukkit.entity.EntityType getType();
}
