package org.bukkit.entity;

import org.bukkit.Location;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.EntityEquipment;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.util.Vector;
import java.util.Collection;
import java.util.Set;

public interface LivingEntity extends Entity {
    double getHealth();
    void setHealth(double health);
    double getMaxHealth();
    void setMaxHealth(double health);
    void damage(double amount);
    void damage(double amount, Entity source);
    double getEyeHeight();
    Location getEyeLocation();
    Vector getVelocity();
    void setVelocity(Vector velocity);
    int getNoDamageTicks();
    void setNoDamageTicks(int ticks);
    int getMaximumAir();
    void setMaximumAir(int ticks);
    int getRemainingAir();
    void setRemainingAir(int ticks);
    float getBodyYaw();
    void setBodyYaw(float yaw);
    boolean hasLineOfSight(Entity other);
    boolean hasLineOfSight(Location location);
    int getArrowsStuck();
    void setArrowsStuck(int arrows);
    int getArrowCooldown();
    void setArrowCooldown(int ticks);
    int getBeeStingerCooldown();
    void setBeeStingerCooldown(int ticks);
    int getBeeStingersStuck();
    void setBeeStingersStuck(int stingers);
    void swingMainHand();
    void swingOffHand();
    void setCollidable(boolean collidable);
    boolean isCollidable();
    void setAI(boolean ai);
    boolean hasAI();
    void setCollarColor(org.bukkit.DyeColor collarColor);
    org.bukkit.DyeColor getCollarColor();
    ItemStack getActiveItem();
    int getActiveItemRemainingTime();
    boolean isGliding();
    void setGliding(boolean gliding);
    boolean isSwimming();
    void setSwimming(boolean swimming);
    boolean isRiptiding();
    void setRiptiding(boolean riptiding);
    boolean isSleeping();
    void setSleeping(boolean sleeping);
    boolean isClimbing();
    boolean isRiding();
    boolean isFrozen();
    void setFrozenTicks(int ticks);
    int getFrozenTicks();
    boolean isHandRaised();
    void setKiller(Player killer);
    Player getKiller();
    Block getTargetBlock(Set<org.bukkit.Material> transparent, int maxDistance);
    Block getTargetBlock(int maxDistance);
    BlockFace getFacing();
    boolean isLeashed();
    void setLeashed(boolean leashed);
    LivingEntity getLeashHolder() throws IllegalStateException;
    boolean setLeashHolder(Entity holder);
    void playPickupItemAnimation(Item item, int count);
    void playPickupItemAnimation(Item item);
    Location getBedLocation();
    PotionEffect getPotionEffect(PotionEffectType type);
    boolean addPotionEffect(PotionEffect effect);
    boolean addPotionEffect(PotionEffect effect, boolean force);
    boolean removePotionEffect(PotionEffectType effect);
    Collection<PotionEffect> getActivePotionEffects();
    boolean isUndead();
    boolean isInWater();
    boolean isInBubbleColumn();
    boolean isInPowderSnow();
    boolean isTameable();
    boolean isSitting();
    void setSitting(boolean sitting);
    int getExpToDrop();
    ItemStack[] getArmorInventoryContents();
    EntityEquipment getEquipment();
    void setCanPickupItems(boolean pickup);
    boolean getCanPickupItems();
}
