package org.bukkit.entity;

public enum SpawnReason {
    BREEDING, BUILD_IRONGOLEM, BUILD_SNOWMAN, BUILD_WITHER, CHUNK_GEN, CURED, CUSTOM,
    DEFAULT, DESPAWN, DISPENSE_EGG, EGG, ENDER_PEARL, EXPLOSION, INFECTION, JOCKEY,
    LIGHTNING, MOUNT, NATURAL, NETHER_PORTAL, OCELOT_BABY, PATROL, RAID, SHEARED,
    SHOULDER_ENTITY, SILVERFISH_BLOCK, SLIME_SPLIT, SPAWNER, SPAWNER_EGG, SPELL,
    TRAP, VILLAGE_DEFENSE, VILLAGE_INVASION, REINFORCEMENT, COMMAND, METAMORPHOSIS,
    ENCHANTMENT, POTION_EFFECT, FROZEN, BEEHIVE
}
