package org.bukkit.inventory;

public enum ItemFlag {
    HIDE_ENCHANTS,
    HIDE_ATTRIBUTES,
    HIDE_UNBREAKABLE,
    HIDE_DESTROYS,
    HIDE_PLACED_ON,
    HIDE_POTION_EFFECTS,
    HIDE_DYE,
    HIDE_ARMOR_TRIM,
    HIDE_ADDITIONAL_TOOLTIP,
    HIDE_TOOLTIP,
    SHOW_TOOLTIP,
    SHOW_ADDITIONAL_TOOLTIP,
    HIDE_STORED_ENCHANTS,
    HIDE_ENCHANTMENT,
    HIDE_ITEM_SPECIFICS;
}
