package org.bukkit;

public enum Effect {
    CLICK1, CLICK2, BOW_FIRE, DOOR_OPEN, DOOR_CLOSE, EXTINGUISH, RECORD_PLAY,
    STEP_SOUND, POTION_BREAK, SMOKE, GHAST_SHRIEK, GHAST_SHOOT, BLAZE_SHOOT,
    ZOMBIE_CHEW_WOOD, ZOMBIE_DESTROY_DOOR, ZOMBIE_INFECT, MOBSPAWNER_FLAMES,
    FIREWORK_SHOOT, VILLAGER_THUNDERCLOUD, ENDER_SIGNAL, BLAZE_FIRE, MOBSPAWNER_FLAMES_ALT,
    STEP_SOUND_ALT, MOBSPAWNER_FLAMES_REMOVE, MOBSPAWNER_FLAMES_ADD, MOBSPAWNER_FLAMES_SPAWN,
    RECORD_PLAY_ALT, ENDER_SIGNAL_REMOVE, ENDER_SIGNAL_ADD, PARTICLE, BOW_FIRE_ALT
}
