package org.bukkit;

public enum Rotation {
    CLOCKWISE_45,
    CLOCKWISE,
    CLOCKWISE_135,
    CLOCKWISE_180,
    CLOCKWISE_225,
    CLOCKWISE_270,
    CLOCKWISE_315,
    NONE,
    FLIPPED_CLOCKWISE_45,
    FLIPPED,
    FLIPPED_CLOCKWISE_135,
    FLIPPED_CLOCKWISE_180,
    FLIPPED_CLOCKWISE_225,
    FLIPPED_CLOCKWISE_270,
    FLIPPED_CLOCKWISE_315,
    FLIPPED_NONE;
}
