package org.bukkit;

public enum TreeType {
    TREE, BIG_TREE, REDWOOD, TALL_REDWOOD, BIRCH, JUNGLE, SMALL_JUNGLE, COCOA_TREE,
    JUNGLE_BUSH, RED_MUSHROOM, BROWN_MUSHROOM, SWAMP, ACACIA, DARK_OAK, MEGA_REDWOOD,
    TALL_BIRCH, CHORUS_PLANT,
    CRIMSON_FUNGUS, WARPED_FUNGUS,
    MANGROVE, TALL_MANGROVE,
    CHERRY,
    PALE_OAK, PALE_OAK_CREAKING,
    AZALEA, AZALEA_TREE,
    MEADOW_PINE, FLOWERING_AZALEA,
    MANGROVE_TREE, TALL_MANGROVE_TREE
}
